export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PROJECTS",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
  SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
};
